language: node_js
node_js:
  - "stable"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - npm install -g phantomjs-prebuilt
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm run-script coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"